CREATE TABLE dishes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    calories      DOUBLE PRECISION                        NOT NULL,
    proteins      DOUBLE PRECISION                        NOT NULL,
    fats          DOUBLE PRECISION                        NOT NULL,
    carbohydrates INTEGER                                 NOT NULL,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

CREATE TABLE meals
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date    date                                    NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_meals PRIMARY KEY (id)
);

CREATE TABLE meals_dishes
(
    meal_id   BIGINT NOT NULL,
    dishes_id BIGINT NOT NULL
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    age                INTEGER                                 NOT NULL,
    height             INTEGER                                 NOT NULL,
    weight             INTEGER                                 NOT NULL,
    goal               SMALLINT                                NOT NULL,
    daily_calorie_norm DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE meals
    ADD CONSTRAINT FK_MEALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE meals_dishes
    ADD CONSTRAINT fk_meadis_on_dish FOREIGN KEY (dishes_id) REFERENCES dishes (id);

ALTER TABLE meals_dishes
    ADD CONSTRAINT fk_meadis_on_meal FOREIGN KEY (meal_id) REFERENCES meals (id);